/**
 * Created by dionid on 21.02.17.
 */


export const FETCH_CARD_LIST_REQUEST = 'FETCH_CARD_LIST_REQUEST';
export const FETCH_CARD_LIST_SUCCESS = 'FETCH_CARD_LIST_SUCCESS';

export const REQUEST_HISTORY_LIST = 'REQUEST_HISTORY_LIST';
export const FETCH_HISTORY_LIST_REQUEST = 'FETCH_HISTORY_LIST_REQUEST';
export const FETCH_HISTORY_LIST_SUCCESS = 'FETCH_HISTORY_LIST_SUCCESS';